import type {
  CalibrationMetadata,
  Checkpoint,
  ColorFragmentEntity,
  FinishPortalEntity,
  HelperEntity,
  SceneManifest,
  SpawnPoint,
  Transform,
} from "@shared/index.js";

function newHelperId(): string {
  if ("randomUUID" in crypto) {
    return `helper-${crypto.randomUUID()}`;
  }
  return `helper-${Date.now()}-${Math.random().toString(16).slice(2)}`;
}

function newCheckpointId(): string {
  if ("randomUUID" in crypto) {
    return `checkpoint-${crypto.randomUUID()}`;
  }
  return `checkpoint-${Date.now()}-${Math.random().toString(16).slice(2)}`;
}

function newExperienceEntityId(prefix: "fragment" | "finish-portal"): string {
  if ("randomUUID" in crypto) return `${prefix}-${crypto.randomUUID()}`;
  return `${prefix}-${Date.now()}-${Math.random().toString(16).slice(2)}`;
}

/**
 * Any manual edit invalidates whatever course-validation status the
 * manifest arrived with — an autogenerated "validated"/"unvalidated"
 * status describes a course this editor didn't produce and can't
 * re-confirm (that requires the actual controller/physics behavior, which
 * lives in src/game, not here). Every mutation below routes through this
 * so the manifest never keeps claiming a validation state that's no
 * longer honest.
 */
export function markManuallyAdjusted(manifest: SceneManifest): SceneManifest {
  return {
    ...manifest,
    courseValidation: {
      status: "manually-adjusted",
      checkedAt: new Date().toISOString(),
      uncertaintyNotes:
        "Adjusted in the level editor; not re-validated against controller/physics behavior. Play-test before relying on it.",
    },
  };
}

export function updateCalibration(manifest: SceneManifest, calibration: CalibrationMetadata): SceneManifest {
  return markManuallyAdjusted({ ...manifest, calibration });
}

export function updateEntityTransform(
  manifest: SceneManifest,
  entityId: string,
  patch: Partial<Transform>,
): SceneManifest {
  return markManuallyAdjusted({
    ...manifest,
    entities: manifest.entities.map((entity) =>
      entity.id === entityId
        ? {
            ...entity,
            transform: {
              position: patch.position ?? entity.transform.position,
              rotation: patch.rotation ?? entity.transform.rotation,
              scale: patch.scale ?? entity.transform.scale,
            },
          }
        : entity,
    ),
  });
}

export function setSpawn(manifest: SceneManifest, spawn: SpawnPoint): SceneManifest {
  return markManuallyAdjusted({ ...manifest, spawn });
}

export function addCheckpoint(
  manifest: SceneManifest,
  params: { position: Checkpoint["position"]; triggerRadius: number; safeRespawn?: SpawnPoint },
): SceneManifest {
  const checkpoint: Checkpoint = {
    id: newCheckpointId(),
    order: manifest.checkpoints.length,
    position: params.position,
    triggerRadius: params.triggerRadius,
    safeRespawn: params.safeRespawn ?? { position: params.position, headingRadians: 0 },
  };
  return markManuallyAdjusted({ ...manifest, checkpoints: [...manifest.checkpoints, checkpoint] });
}

/** Removes a checkpoint and renumbers the rest to stay unique/ascending
 * from 0, per the manifest's documented invariant. */
export function removeCheckpoint(manifest: SceneManifest, checkpointId: string): SceneManifest {
  const remaining = manifest.checkpoints
    .filter((c) => c.id !== checkpointId)
    .sort((a, b) => a.order - b.order)
    .map((c, index) => ({ ...c, order: index }));
  return markManuallyAdjusted({ ...manifest, checkpoints: remaining });
}

export function updateCheckpoint(
  manifest: SceneManifest,
  checkpointId: string,
  patch: Partial<Omit<Checkpoint, "id" | "order">>,
): SceneManifest {
  return markManuallyAdjusted({
    ...manifest,
    checkpoints: manifest.checkpoints.map((c) => (c.id === checkpointId ? { ...c, ...patch } : c)),
  });
}

/** Swaps a checkpoint's order with its neighbor in the given direction,
 * keeping the 0..n-1 ascending invariant intact. */
export function reorderCheckpoint(
  manifest: SceneManifest,
  checkpointId: string,
  direction: "up" | "down",
): SceneManifest {
  const sorted = [...manifest.checkpoints].sort((a, b) => a.order - b.order);
  const index = sorted.findIndex((c) => c.id === checkpointId);
  if (index === -1) return manifest;
  const swapWith = direction === "up" ? index - 1 : index + 1;
  if (swapWith < 0 || swapWith >= sorted.length) return manifest;
  const a = sorted[index]!;
  const b = sorted[swapWith]!;
  sorted[index] = { ...b, order: a.order };
  sorted[swapWith] = { ...a, order: b.order };
  return markManuallyAdjusted({ ...manifest, checkpoints: sorted });
}

function restorationSteps(count: number): number[] {
  return Array.from({ length: count }, (_, index) => (index + 1) / count);
}

export function addColorFragment(
  manifest: SceneManifest,
  position: ColorFragmentEntity["transform"]["position"],
): SceneManifest {
  if (!manifest.experience) return manifest;
  const collectible: ColorFragmentEntity = {
    id: newExperienceEntityId("fragment"),
    kind: "color-fragment",
    transform: { position, rotation: [0, 0, 0, 1], scale: [0.22, 0.22, 0.22] },
    triggerRadius: 0.45,
    color: "#FFD93D",
    order: manifest.experience.collectibles.length,
    restorationAmount: 1,
  };
  const collectibles = [...manifest.experience.collectibles, collectible].map((item, index, all) => ({
    ...item,
    order: index,
    restorationAmount: 1 / all.length,
  }));
  const mode = manifest.experience.mode;
  const nextMode =
    mode.kind === "collect"
      ? {
          ...mode,
          requiredCollectibleIds: [...mode.requiredCollectibleIds, collectible.id],
          requiredCount: mode.requiredCount + 1,
          restorationSteps: restorationSteps(mode.requiredCount + 1),
        }
      : mode.kind === "explore"
        ? { ...mode, optionalCollectibleIds: [...mode.optionalCollectibleIds, collectible.id] }
        : mode;
  return markManuallyAdjusted({
    ...manifest,
    experience: { ...manifest.experience, mode: nextMode, collectibles },
  });
}

export function updateColorFragment(
  manifest: SceneManifest,
  collectibleId: string,
  patch: Partial<Omit<ColorFragmentEntity, "id" | "kind" | "order">>,
): SceneManifest {
  if (!manifest.experience || !manifest.experience.collectibles.some((item) => item.id === collectibleId)) {
    return manifest;
  }
  return markManuallyAdjusted({
    ...manifest,
    experience: {
      ...manifest.experience,
      collectibles: manifest.experience.collectibles.map((item) =>
        item.id === collectibleId ? { ...item, ...patch } : item,
      ),
    },
  });
}

export function removeColorFragment(manifest: SceneManifest, collectibleId: string): SceneManifest {
  if (!manifest.experience || !manifest.experience.collectibles.some((item) => item.id === collectibleId)) {
    return manifest;
  }
  const collectibles = manifest.experience.collectibles
    .filter((item) => item.id !== collectibleId)
    .map((item, index, all) => ({
      ...item,
      order: index,
      restorationAmount: all.length === 0 ? item.restorationAmount : 1 / all.length,
    }));
  const mode = manifest.experience.mode;
  const nextMode =
    mode.kind === "collect"
      ? (() => {
          const requiredCollectibleIds = mode.requiredCollectibleIds.filter((id) => id !== collectibleId);
          return {
            ...mode,
            requiredCollectibleIds,
            requiredCount: requiredCollectibleIds.length,
            restorationSteps: restorationSteps(requiredCollectibleIds.length),
          };
        })()
      : mode.kind === "explore"
        ? { ...mode, optionalCollectibleIds: mode.optionalCollectibleIds.filter((id) => id !== collectibleId) }
        : mode;
  return markManuallyAdjusted({
    ...manifest,
    experience: { ...manifest.experience, mode: nextMode, collectibles },
  });
}

export function addFinishPortal(manifest: SceneManifest, position: FinishPortalEntity["transform"]["position"]): SceneManifest {
  if (!manifest.experience || manifest.experience.finishPortal) return manifest;
  const portal: FinishPortalEntity = {
    id: newExperienceEntityId("finish-portal"),
    kind: "finish-portal",
    transform: { position, rotation: [0, 0, 0, 1], scale: [0.8, 1.2, 0.25] },
    triggerRadius: 0.75,
    activation:
      manifest.experience.mode.kind === "collect"
        ? "all-required-collectibles"
        : manifest.experience.mode.kind === "race"
          ? "all-race-checkpoints"
          : "always",
    inactiveColor: "#6D6780",
    activeColor: "#9B5DE5",
  };
  const mode = manifest.experience.mode;
  const nextMode =
    mode.kind === "collect" || mode.kind === "race" ? { ...mode, finishPortalId: portal.id } : mode;
  return markManuallyAdjusted({
    ...manifest,
    experience: { ...manifest.experience, mode: nextMode, finishPortal: portal },
  });
}

export function updateFinishPortal(
  manifest: SceneManifest,
  patch: Partial<Omit<FinishPortalEntity, "id" | "kind">>,
): SceneManifest {
  if (!manifest.experience?.finishPortal) return manifest;
  return markManuallyAdjusted({
    ...manifest,
    experience: {
      ...manifest.experience,
      finishPortal: { ...manifest.experience.finishPortal, ...patch },
    },
  });
}

export function removeFinishPortal(manifest: SceneManifest): SceneManifest {
  if (!manifest.experience?.finishPortal || manifest.experience.mode.kind === "collect") return manifest;
  const mode = manifest.experience.mode;
  const nextMode =
    mode.kind === "race"
      ? (() => {
          const { finishPortalId: _finishPortalId, ...withoutFinishPortal } = mode;
          return withoutFinishPortal;
        })()
      : mode;
  return markManuallyAdjusted({
    ...manifest,
    experience: { ...manifest.experience, mode: nextMode, finishPortal: null },
  });
}

export function addHelperEntity(
  manifest: SceneManifest,
  params: Pick<HelperEntity, "kind" | "transform" | "dimensions" | "collider">,
): SceneManifest {
  const helper: HelperEntity = {
    id: newHelperId(),
    kind: params.kind,
    transform: params.transform,
    dimensions: params.dimensions,
    collider: params.collider,
    addedBy: "game",
  };
  return markManuallyAdjusted({ ...manifest, entities: [...manifest.entities, helper] });
}

export function removeHelperEntity(manifest: SceneManifest, entityId: string): SceneManifest {
  return markManuallyAdjusted({
    ...manifest,
    entities: manifest.entities.filter((entity) => entity.id !== entityId),
  });
}

export function updateHelperDimensions(
  manifest: SceneManifest,
  entityId: string,
  dimensions: HelperEntity["dimensions"],
): SceneManifest {
  return markManuallyAdjusted({
    ...manifest,
    entities: manifest.entities.map((entity) =>
      entity.id === entityId && entity.kind !== "generated-mesh"
        ? {
            ...entity,
            dimensions,
            collider:
              entity.kind === "ramp"
                ? { kind: "triangle-mesh" as const }
                : {
                    kind: "box" as const,
                    halfExtents: [dimensions[0] / 2, dimensions[1] / 2, dimensions[2] / 2],
                  },
          }
        : entity,
    ),
  });
}
