/**
 * The character's face, drawn procedurally onto a canvas at runtime.
 *
 * PROVENANCE: original art, generated by the code below. No image file, no
 * download, no provider call. Drawing the face instead of modelling it keeps
 * the head one smooth surface (eyes sunk into geometry read as holes at this
 * size) and lets the expression change without touching the mesh.
 *
 * The atlas is mostly flat white: every body vertex samples the white corner,
 * so one texture and one material cover the whole character. Only the head's
 * cylindrical UVs land in the art region, which is why the head is the only
 * part with `faceMapped: true` in `characterDesign.ts`.
 */

import * as THREE from "three";
import { FACE_UV_ORIGIN, FACE_UV_SPAN } from "./characterGeometry.js";
import { PALETTE } from "./characterDesign.js";

const SIZE = 512;

/** UV → canvas pixel. Canvas Y is flipped relative to UV V. */
function px(u: number): number {
  return u * SIZE;
}
function py(v: number): number {
  return (1 - v) * SIZE;
}

/** Head sweep parameter (0 at the neck, 1 at the crown) → atlas V. */
function headV(t: number): number {
  return FACE_UV_ORIGIN + t * FACE_UV_SPAN;
}

/** Angle around the head in turns (0 = dead ahead, ± = left/right) → atlas U.
 * The head's ring vertices run from theta = -PI to +PI across the art region,
 * so dead ahead is the middle of that span. */
function headU(turns: number): number {
  return FACE_UV_ORIGIN + (0.5 + turns) * FACE_UV_SPAN;
}

function eye(
  context: CanvasRenderingContext2D,
  centreU: number,
  centreV: number,
  radius: number,
): void {
  const cx = px(centreU);
  const cy = py(centreV);

  context.fillStyle = "#241d33";
  context.beginPath();
  context.ellipse(cx, cy, radius, radius * 1.18, 0, 0, Math.PI * 2);
  context.fill();

  // Two highlights: a large one for life, a small one for sparkle. Without
  // these the eyes read as flat holes once the character is a few pixels tall.
  context.fillStyle = "#ffffff";
  context.beginPath();
  context.ellipse(cx - radius * 0.3, cy - radius * 0.42, radius * 0.34, radius * 0.34, 0, 0, Math.PI * 2);
  context.fill();
  context.beginPath();
  context.ellipse(cx + radius * 0.34, cy + radius * 0.3, radius * 0.16, radius * 0.16, 0, 0, Math.PI * 2);
  context.fill();
}

export function drawFaceAtlas(context: CanvasRenderingContext2D): void {
  context.fillStyle = "#ffffff";
  context.fillRect(0, 0, SIZE, SIZE);

  // Cheeks first, so the eyes and mouth sit on top of them.
  const cheekY = headV(0.42);
  context.fillStyle = "rgba(255, 138, 120, 0.42)";
  for (const turns of [-0.105, 0.105]) {
    context.beginPath();
    context.ellipse(px(headU(turns)), py(cheekY), SIZE * 0.035, SIZE * 0.023, 0, 0, Math.PI * 2);
    context.fill();
  }

  const eyeV = headV(0.52);
  eye(context, headU(-0.062), eyeV, SIZE * 0.042);
  eye(context, headU(0.062), eyeV, SIZE * 0.042);

  // Brows: short, slightly raised, which is most of the character's warmth.
  context.strokeStyle = "#3a2f4d";
  context.lineWidth = SIZE * 0.012;
  context.lineCap = "round";
  for (const [turns, tilt] of [
    [-0.062, -1],
    [0.062, 1],
  ] as const) {
    const bx = px(headU(turns));
    const by = py(headV(0.63));
    context.beginPath();
    context.moveTo(bx - SIZE * 0.032, by + SIZE * 0.006 * tilt);
    context.quadraticCurveTo(bx, by - SIZE * 0.014, bx + SIZE * 0.032, by - SIZE * 0.006 * tilt);
    context.stroke();
  }

  // Mouth: an open, upturned curve rather than a line, so it reads at a
  // distance and from slightly above (the default camera pitch).
  context.strokeStyle = "#5a3b3b";
  context.lineWidth = SIZE * 0.014;
  const mx = px(headU(0));
  const my = py(headV(0.33));
  context.beginPath();
  context.moveTo(mx - SIZE * 0.028, my);
  context.quadraticCurveTo(mx, my + SIZE * 0.028, mx + SIZE * 0.028, my);
  context.stroke();

  // Knitted-cap texture: a band of stitches along the brim, which is what
  // stops the cap reading as a plain painted sphere.
  context.strokeStyle = "rgba(210, 186, 160, 0.7)";
  context.lineWidth = SIZE * 0.006;
  for (let i = 0; i <= 36; i += 1) {
    const turns = -0.5 + i / 36;
    const x = px(headU(turns));
    context.beginPath();
    context.moveTo(x, py(headV(0.76)));
    context.lineTo(x, py(headV(0.86)));
    context.stroke();
  }

  // Goggle strap shading just under the brim.
  context.fillStyle = PALETTE.goggles;
  context.globalAlpha = 0.18;
  context.fillRect(px(FACE_UV_ORIGIN), py(headV(0.74)), px(FACE_UV_SPAN), SIZE * 0.012);
  context.globalAlpha = 1;
}

/**
 * Creates the face texture. Returns `null` where no canvas exists (unit tests,
 * SSR); the character then renders with vertex colours only, which is a
 * complete, if plainer, face-less fallback rather than a crash.
 */
export function createFaceTexture(): THREE.Texture | null {
  if (typeof document === "undefined") return null;
  const canvas = document.createElement("canvas");
  canvas.width = SIZE;
  canvas.height = SIZE;
  const context = canvas.getContext("2d");
  if (!context) return null;

  drawFaceAtlas(context);

  const texture = new THREE.CanvasTexture(canvas);
  texture.colorSpace = THREE.SRGBColorSpace;
  texture.anisotropy = 4;
  texture.needsUpdate = true;
  return texture;
}
