/**
 * The character's face, drawn procedurally onto a canvas at runtime.
 *
 * PROVENANCE: original art, generated by the code below. No image file, no
 * download, no provider call. Drawing the face instead of modelling it keeps
 * the head one smooth surface (eyes sunk into geometry read as holes at this
 * size) and lets the expression change without touching the mesh.
 *
 * The atlas is mostly flat white: every body vertex samples the white corner,
 * so one texture and one material cover the whole character. Only the head's
 * cylindrical UVs land in the art region, which is why the head is the only
 * part with `faceMapped: true` in `characterDesign.ts`.
 */

import * as THREE from "three";
import { FACE_UV_ORIGIN, FACE_UV_SPAN } from "./characterGeometry.js";
import { FACE_ANCHORS, headSurfaceV } from "./characterDesign.js";

const SIZE = 512;

/** UV → canvas pixel. Canvas Y is flipped relative to UV V. */
function px(u: number): number {
  return u * SIZE;
}
function py(v: number): number {
  return (1 - v) * SIZE;
}

/**
 * Height in character units → atlas V. Goes through `headSurfaceV` rather than
 * treating V as height directly: the head's rings are not evenly spaced, so
 * the two are not the same thing and eyeballing it puts the art on the wrong
 * feature.
 */
function headV(height: number): number {
  return FACE_UV_ORIGIN + headSurfaceV(height) * FACE_UV_SPAN;
}

/** Angle around the head in turns (0 = dead ahead, ± = left/right) → atlas U.
 * The head's ring vertices run from theta = -PI to +PI across the art region,
 * so dead ahead is the middle of that span. */
function headU(turns: number): number {
  return FACE_UV_ORIGIN + (0.5 + turns) * FACE_UV_SPAN;
}

/**
 * The head's UVs wrap a full turn across the art region horizontally but only
 * the head's height vertically, so one unit of U covers roughly three times as
 * much surface as one unit of V. Anything drawn round comes out three times too
 * wide on the model — which is how the first pass produced a bandit mask
 * instead of a pair of eyes. Divide every horizontal extent by this.
 */
const U_STRETCH = 3.1;

/** Draws an ellipse that is actually round once projected onto the head. */
function roundOnHead(
  context: CanvasRenderingContext2D,
  centreU: number,
  centreV: number,
  radius: number,
  aspect = 1,
): void {
  context.ellipse(
    px(centreU),
    py(centreV),
    (SIZE * radius * aspect) / U_STRETCH,
    SIZE * radius,
    0,
    0,
    Math.PI * 2,
  );
}

function eye(
  context: CanvasRenderingContext2D,
  centreU: number,
  centreV: number,
  radius: number,
): void {
  const cx = px(centreU);
  const cy = py(centreV);
  const rx = (SIZE * radius * 1.12) / U_STRETCH;
  const ry = SIZE * radius;

  context.fillStyle = "#241d33";
  context.beginPath();
  roundOnHead(context, centreU, centreV, radius, 1.12);
  context.fill();

  // Two highlights: a large one for life, a small one for sparkle. Without
  // these the eyes read as flat holes once the character is a few pixels tall.
  context.fillStyle = "#ffffff";
  context.beginPath();
  context.ellipse(cx - rx * 0.3, cy - ry * 0.4, rx * 0.36, ry * 0.36, 0, 0, Math.PI * 2);
  context.fill();
  context.beginPath();
  context.ellipse(cx + rx * 0.34, cy + ry * 0.3, rx * 0.17, ry * 0.17, 0, 0, Math.PI * 2);
  context.fill();
}

export function drawFaceAtlas(context: CanvasRenderingContext2D): void {
  context.fillStyle = "#ffffff";
  context.fillRect(0, 0, SIZE, SIZE);

  const EYE_TURNS = 0.062;

  // Cheeks first, so the eyes and mouth sit on top of them.
  context.fillStyle = "rgba(255, 126, 104, 0.4)";
  for (const turns of [-0.115, 0.115]) {
    context.beginPath();
    roundOnHead(context, headU(turns), headV(FACE_ANCHORS.cheek), 0.017, 2.1);
    context.fill();
  }

  const eyeV = headV(FACE_ANCHORS.eyes);
  eye(context, headU(-EYE_TURNS), eyeV, 0.034);
  eye(context, headU(EYE_TURNS), eyeV, 0.034);

  // Brows: short, slightly raised, which is most of the character's warmth.
  const browHalfWidth = (SIZE * 0.03) / U_STRETCH;
  context.strokeStyle = "#4a3a5e";
  context.lineWidth = SIZE * 0.008;
  context.lineCap = "round";
  for (const [turns, tilt] of [
    [-EYE_TURNS, -1],
    [EYE_TURNS, 1],
  ] as const) {
    const bx = px(headU(turns));
    const by = py(headV(FACE_ANCHORS.brow));
    context.beginPath();
    context.moveTo(bx - browHalfWidth, by + SIZE * 0.005 * tilt);
    context.quadraticCurveTo(bx, by - SIZE * 0.011, bx + browHalfWidth, by - SIZE * 0.005 * tilt);
    context.stroke();
  }

  // Mouth: an open, upturned curve rather than a line, so it reads at a
  // distance and from slightly above (the default camera pitch).
  const mouthHalfWidth = (SIZE * 0.05) / U_STRETCH;
  context.strokeStyle = "#8a4c3e";
  context.lineWidth = SIZE * 0.009;
  const mx = px(headU(0));
  const my = py(headV(FACE_ANCHORS.mouth));
  context.beginPath();
  context.moveTo(mx - mouthHalfWidth, my);
  context.quadraticCurveTo(mx, my + SIZE * 0.022, mx + mouthHalfWidth, my);
  context.stroke();

  // Knitted-cap texture: a band of stitches over the crown, which is what
  // stops the cap reading as a plain painted sphere. Drawn dark because the
  // cap's vertex colour multiplies through it.
  context.strokeStyle = "rgba(120, 175, 172, 0.85)";
  context.lineWidth = SIZE * 0.005;
  for (let i = 0; i <= 44; i += 1) {
    const turns = -0.5 + i / 44;
    const x = px(headU(turns));
    context.beginPath();
    context.moveTo(x, py(headV(FACE_ANCHORS.capBrim)));
    context.lineTo(x, py(headV(FACE_ANCHORS.capCrown)));
    context.stroke();
  }

  // A ribbed band right on the brim, so the cap has an edge of its own.
  context.strokeStyle = "rgba(20, 70, 70, 0.55)";
  context.lineWidth = SIZE * 0.009;
  context.beginPath();
  context.moveTo(px(FACE_UV_ORIGIN), py(headV(FACE_ANCHORS.capBrim)));
  context.lineTo(px(FACE_UV_ORIGIN + FACE_UV_SPAN), py(headV(FACE_ANCHORS.capBrim)));
  context.stroke();
}

/**
 * Creates the face texture. Returns `null` where no canvas exists (unit tests,
 * SSR); the character then renders with vertex colours only, which is a
 * complete, if plainer, face-less fallback rather than a crash.
 */
export function createFaceTexture(): THREE.Texture | null {
  if (typeof document === "undefined") return null;
  const canvas = document.createElement("canvas");
  canvas.width = SIZE;
  canvas.height = SIZE;
  const context = canvas.getContext("2d");
  if (!context) return null;

  drawFaceAtlas(context);

  const texture = new THREE.CanvasTexture(canvas);
  texture.colorSpace = THREE.SRGBColorSpace;
  texture.anisotropy = 4;
  texture.needsUpdate = true;
  return texture;
}
